//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenges.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenges_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Challenges_Table()
        {
            this.Responses_Table = new HashSet<Responses_Table>();
        }
    
        public long Id { get; set; }
        public bool Completed { get; set; }
        public int Id_User_From { get; set; }
        public int Id_User_To { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Responses_Table> Responses_Table { get; set; }
    }
}
