//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenges.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighestReputation
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Nickname { get; set; }
        public int Reputation { get; set; }
    }
}
