//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenges.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChallengesDBEntities : DbContext
    {
        public ChallengesDBEntities()
            : base("name=ChallengesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Challenges_Table> Challenges_Table { get; set; }
        public virtual DbSet<Responses_Table> Responses_Table { get; set; }
        public virtual DbSet<HighestReputation> HighestReputation { get; set; }
    }
}
