//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Challenges.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responses_Table
    {
        public long Id { get; set; }
        public long Id_Challenges_Table { get; set; }
    
        public virtual Challenges_Table Challenges_Table { get; set; }
    }
}
